DROP DATABASE IF EXISTS Movies; 
CREATE DATABASE Movies;
USE Movies;

CREATE TABLE features(
id INT AUTO_INCREMENT PRIMARY KEY,
title varchar (255) NOT NULL,
feature_year YEAR NOT NULL,
feature_type ENUM("Movie", "TV_Show") NOT NULL
);

CREATE TABLE features_work (
work_id INT AUTO_INCREMENT PRIMARY KEY,
feature_id INT  NOT NULL,
person_name VARCHAR(255) NOT NULL,
feature_role ENUM("Actor","Director") NOT NULL,
FOREIGN KEY (feature_id) REFERENCES features (id)
);

CREATE TABLE features_role(
role_id INT AUTO_INCREMENT PRIMARY KEY,
feature_work_id INT NOT NULL,
character_name varchar (255) NOT NULL,
FOREIGN KEY (feature_work_id) REFERENCES features_work(work_id)
);

INSERT INTO features (title,feature_year,feature_type) VALUES
("Dr. No", 1962, "Movie"),
("From Russia with Love", 1963, "Movie"),
("Goldfinger", 1964, "Movie"),
("Thunderball", 1965, "Movie"),
("You Only Live Twice", 1967, "Movie"),
("On Her Majesty's Secret Service", 1969, "Movie"),
("Diamonds Are Forever", 1971, "Movie"),
("Live and Let Die", 1973, "Movie"),
("The Man with the Golden Gun", 1974, "Movie"),
("The Spy Who Loved Me", 1977, "Movie"),
("Moonraker", 1979, "Movie"),
("For Your Eyes Only", 1981, "Movie"),
("Octopussy", 1983, "Movie"),
("A View to a Kill", 1985, "Movie"),
("The Living Daylights", 1987, "Movie"),
("Licence to Kill", 1989, "Movie"),
("GoldenEye", 1995, "Movie"),
("Tomorrow Never Dies", 1997, "Movie"),
("The World Is Not Enough", 1999, "Movie"),
("Die Another Day", 2002, "Movie"),
("Casino Royale", 2006, "Movie"),
("Quantum of Solace", 2008, "Movie"),
("Skyfall", 2012, "Movie"),
("Spectre", 2015, "Movie"),
("No Time to Die", 2021, "Movie"),
("Iron Man", 2008, "Movie"),
("The Incredible Hulk", 2008, "Movie"),
("Iron Man 2", 2010, "Movie"),
("Captain America: The First Avenger", 2011, "Movie"),
("Captain America: Civil War", 2016, "Movie"),
("Doctor Strange", 2016, "Movie"),
("Guardians of the Galaxy Vol. 2", 2017, "Movie"),
("Spider-Man: Homecoming", 2017, "Movie"),
("Thor: Ragnarok", 2017, "Movie"),
("Black Panther", 2018, "Movie"),
("Avengers: Infinity War", 2018, "Movie"),
("Ant-Man and the Wasp", 2018, "Movie"),
("Captain Marvel", 2019, "Movie"),
("The Simpsons", 1989, "TV_Show"),
("Rick and Morty", 2013, "TV_Show"),
("The Good Doctor", 2017, "TV_Show"),
("Planet Earth II", 2016, "TV_Show"),
("Breaking Bad", 2008, "TV_Show"),
("Planet Earth", 2006, "TV_Show"),
("Band of Brothers", 2001, "TV_Show"),
("Chernobyl", 2019, "TV_Show"),
("The Wire", 2002, "TV_Show"),
("Blue Planet II", 2017, "TV_Show"),
("Avatar: The Last Airbender", 2005, "TV_Show"),
("Cosmos", 2014, "TV_Show");


INSERT INTO features_work (feature_id,person_name,feature_role) VALUES
(1, "Sean Connery", "Actor"),
(1, "Terence Young", "Director"),
(2, "Sean Connery", "Actor"),
(2, "Terence Young", "Director"),
(3, "Sean Connery", "Actor"),
(3, "Guy Hamilton", "Director"),
(4, "Sean Connery", "Actor"),
(4, "Terence Young", "Director"),
(5, "Sean Connery", "Actor"),
(5, "Lewis Gilbert", "Director"),
(6, "George Lazenby", "Actor"),
(6, "Peter R. Hunt", "Director"),
(7, "Sean Connery", "Actor"),
(7, "Guy Hamilton", "Director"),
(8, "Roger Moore", "Actor"),
(8, "Guy Hamilton", "Director"),
(9, "Roger Moore", "Actor"),
(9, "Guy Hamilton", "Director"),
(10, "Roger Moore", "Actor"),
(10, "Lewis Gilbert", "Director"),
(11, "Roger Moore", "Actor"),
(11, "Lewis Gilbert", "Director"),
(12, "Roger Moore", "Actor"),
(12, "John Glen", "Director"),
(13, "Roger Moore", "Actor"),
(13, "John Glen", "Director"),
(14, "Roger Moore", "Actor"),
(14, "John Glen", "Director"),
(15, "Timothy Dalton", "Actor"),
(15, "John Glen", "Director"),
(16, "Timothy Dalton", "Actor"),
(16, "John Glen", "Director"),
(17, "Pierce Brosnan", "Actor"),
(17, "Martin Campbell", "Director"),
(18, "Pierce Brosnan", "Actor"),
(18, "Roger Spottiswoo", "Director"),
(19, "Pierce Brosnan", "Actor"),
(19, "JMichael Apted", "Director"),
(20, "Pierce Brosnan", "Actor"),
(20, "Lee Tamahori", "Director"),
(21, "Daniel Craig", "Actor"),
(21, "Martin Campbell", "Director"),
(22, "Daniel Craig", "Actor"),
(22, "Marc Forster", "Director"),
(23, "Daniel Craig", "Actor"),
(23, "Sam Mendes", "Director"),
(24, "Daniel Craig", "Actor"),
(24, "Sam Mendes", "Director"),
(25, "Daniel Craig", "Actor"),
(25, "Cary Joji Fukunaga", "Director"),
(26, "Robert Downey Jr.", "Actor"),
(26, "Jon Favreau", "Director"),
(27, "Edward Norton.", "Actor"),
(27, "Louis Leterrier", "Director"),
(28, "Robert Downey Jr.", "Actor"),
(28, "Jon Favreau", "Director"),
(29, "Chris Evans", "Actor"),
(29, "Joe Johnston", "Director"),
(30, "Chris Evans", "Actor"),
(30, "Anthony Russo", "Director"),
(30, "Joe Russo", "Director"),
(31, "Benedict Cumberbatch", "Actor"),
(31, "Scott Derrickson", "Director"),
(32, "Chris Pratt", "Actor"),
(32, "James Gunn", "Director"),
(33, "Tom Holland", "Actor"),
(33, "Jon Watts", "Director"),
(34, "Chris Hemsworth", "Actor"),
(34, "Taika Waititi", "Director"),
(35, "Chadwick Boseman", "Actor"),
(35, "Ryan Coogler", "Director"),
(36, "Robert Downey Jr.", "Actor"),
(36, "Anthony Russo", "Director"),
(36, "Joe Russo", "Director"),
(37, "Paul Rudd", "Actor"),
(37, "Peyton Reed", "Director"),
(38, "Brie Larson", "Actor"),
(38, "Anna Boden", "Director"),
(38, "Ryan Fleck", "Director"),
(39, "The Simpsons Faimily", "Actor"),
(49, "Matt Groening", "Director"),
(40, "Rick Sanchez", "Actor"),
(40, "Justin Rolland", "Director"),
(40, "Dan Hamon", "Director"),
(41, "Freddie Highmore", "Actor"),
(41, "David Shore", "Director"),
(42, "David Attenborough", "Actor"),
(42, "Justin Anderson", "Director"),
(43, "Bryan Cranston", "Actor"),
(43, "Michelle MacLaren", "Director"),
(44, "Sigourney Weaver", "Actor"),
(44, "Alastair Fothergill", "Director"),
(45, "Scott Grimes", "Actor"),
(45, "David Frankel", "Director"),
(46, "Jessie Buckley", "Actor"),
(46, "Johan Renck", "Director"),
(47, "Dominic West", "Actor"),
(47, "Joe Chappelle", "Director"),
(48, "David Attenborough", "Actor"),
(48, "Yoland Bosiger", "Director"),
(49, "Dee Bradley Baker", "Actor"),
(49, "Giancarlo Volpe", "Director"),
(50, "Neil deGrasse Tyson", "Actor"),
(50, "Brannon Braga", "Director");

INSERT INTO features_role (feature_work_id, character_name) VALUES
(1, "James Bond"),
(3, "James Bond"),
(5, "James Bond"),
(7, "James Bond"),
(9, "James Bond"),
(11, "James Bond"),
(13, "James Bond"),
(15, "James Bond"),
(17, "James Bond"),
(19, "James Bond"),
(21, "James Bond"),
(23, "James Bond"),
(25, "James Bond"),
(27, "James Bond"),
(29, "James Bond"),
(31, "James Bond"),
(33, "James Bond"),
(35, "James Bond"),
(37, "James Bond"),
(39, "James Bond"),
(41, "James Bond"),
(43, "James Bond"),
(45, "James Bond"),
(47, "James Bond"),
(49, "James Bond"),
(51, "Tony Stark/Iron man"),
(53, "Bruce Banner/Hulk"),
(55, "Tony Stark/Iron man"),
(57, "Steve Rogers/Captain America"),
(59, "Steve Rogers/Captain America"),
(62, "neurosurgeon Stephen Strange"),
(64, "Peter Quill / Star-Lord"),
(66, "Peter Parker / Spider-Man"),
(68, "Thor alongside"),
(70, "T'Challa / Black Panther"),
(72, "Tony Stark/Iron man"),
(75, "Scott Lang/Ant-Man"),
(77, "Carol Danvers/Captain Marvel"),
(80, "Simpsons"),
(82, "Rick Sanchez"),
(85, "Shaun Murphy"),
(87, "Self - Narrator"),
(89, "Walter White"),
(91, "Narrator - US Version"),
(93, "Donald G. Malarkey"),
(95, "Lyudmilla Ignatenko"),
(97, "Detective James 'Jimmy' McNulty"),
(99, "Self - Narrator"),
(101, "Appa"),
(103, "Self - Host");

-- use Movies;
-- select * from features; 
-- select * from features_work; 
select * from features_role; 
